export settings=movSLAM
export run=ofmv usemv=1 confext=".ofmv" dspath=/media/chris/BigFiles/Thesis_Data/compressed_datasets/h264/$settings
export ds=EMH01    dsname=MH_01_easy_$settings	 calib=data/euroc/euroc_ds_calib.json      config=data/euroc/euroc_config_vo$confext.json
echo ">>> [$settings - $run - $ds]" && time ./build/basalt_vio --show-gui 0 --deterministic 1 --use-imu 0 --use-mvs $usemv --dataset-path $dspath/$dsname  --dataset-type euroc --cam-calib $calib --config-path $config --save-trajectory euroc 2>&1 | tee output.log; mkdir -p results/$settings/$run/$ds/ && mv trajectory.csv results/$settings/$run/$ds/tracking.csv && mv output.log *.json results/$settings/$run/$ds/
export ds=EMH02    dsname=MH_02_easy_$settings              calib=data/euroc/euroc_ds_calib.json      config=data/euroc/euroc_config_vo$confext.json
echo ">>> [$settings - $run - $ds]" && time ./build/basalt_vio --show-gui 0 --deterministic 1 --use-imu 0 --use-mvs $usemv --dataset-path $dspath/$dsname  --dataset-type euroc --cam-calib $calib --config-path $config --save-trajectory euroc 2>&1 | tee output.log; mkdir -p results/$settings/$run/$ds/ && mv trajectory.csv results/$settings/$run/$ds/tracking.csv && mv output.log *.json results/$settings/$run/$ds/
export ds=EV101    dsname=V1_01_easy_$settings              calib=data/euroc/euroc_ds_calib.json      config=data/euroc/euroc_config_vo$confext.json
echo ">>> [$settings - $run - $ds]" && time ./build/basalt_vio --show-gui 0 --deterministic 1 --use-imu 0 --use-mvs $usemv --dataset-path $dspath/$dsname  --dataset-type euroc --cam-calib $calib --config-path $config --save-trajectory euroc 2>&1 | tee output.log; mkdir -p results/$settings/$run/$ds/ && mv trajectory.csv results/$settings/$run/$ds/tracking.csv && mv output.log *.json results/$settings/$run/$ds/
export ds=EV201    dsname=V2_01_easy_$settings              calib=data/euroc/euroc_ds_calib.json      config=data/euroc/euroc_config_vo$confext.json
echo ">>> [$settings - $run - $ds]" && time ./build/basalt_vio --show-gui 0 --deterministic 1 --use-imu 0 --use-mvs $usemv --dataset-path $dspath/$dsname  --dataset-type euroc --cam-calib $calib --config-path $config --save-trajectory euroc 2>&1 | tee output.log; mkdir -p results/$settings/$run/$ds/ && mv trajectory.csv results/$settings/$run/$ds/tracking.csv && mv output.log *.json results/$settings/$run/$ds/
export ds=MGO05    dsname=MGO05_inspect_easy_$settings      calib=data/msd/msdmg_calib.json           config=data/msd/msdmg_config_vo$confext.json
echo ">>> [$settings - $run - $ds]" && time ./build/basalt_vio --show-gui 0 --deterministic 1 --use-imu 0 --use-mvs $usemv --dataset-path $dspath/$dsname  --dataset-type euroc --cam-calib $calib --config-path $config --save-trajectory euroc 2>&1 | tee output.log; mkdir -p results/$settings/$run/$ds/ && mv trajectory.csv results/$settings/$run/$ds/tracking.csv && mv output.log *.json results/$settings/$run/$ds/
export ds=MGO07    dsname=MGO07_mapping_easy_$settings      calib=data/msd/msdmg_calib.json           config=data/msd/msdmg_config_vo$confext.json
echo ">>> [$settings - $run - $ds]" && time ./build/basalt_vio --show-gui 0 --deterministic 1 --use-imu 0 --use-mvs $usemv --dataset-path $dspath/$dsname  --dataset-type euroc --cam-calib $calib --config-path $config --save-trajectory euroc 2>&1 | tee output.log; mkdir -p results/$settings/$run/$ds/ && mv trajectory.csv results/$settings/$run/$ds/tracking.csv && mv output.log *.json results/$settings/$run/$ds/
export ds=MIO05    dsname=MIO05_inspect_easy_$settings      calib=data/msd/msdmi_calib.json           config=data/msd/msdmi_config_vo$confext.json
echo ">>> [$settings - $run - $ds]" && time ./build/basalt_vio --show-gui 0 --deterministic 1 --use-imu 0 --use-mvs $usemv --dataset-path $dspath/$dsname  --dataset-type euroc --cam-calib $calib --config-path $config --save-trajectory euroc 2>&1 | tee output.log; mkdir -p results/$settings/$run/$ds/ && mv trajectory.csv results/$settings/$run/$ds/tracking.csv && mv output.log *.json results/$settings/$run/$ds/
export ds=MIO07    dsname=MIO07_mapping_easy_$settings      calib=data/msd/msdmi_calib.json           config=data/msd/msdmi_config_vo$confext.json
echo ">>> [$settings - $run - $ds]" && time ./build/basalt_vio --show-gui 0 --deterministic 1 --use-imu 0 --use-mvs $usemv --dataset-path $dspath/$dsname  --dataset-type euroc --cam-calib $calib --config-path $config --save-trajectory euroc 2>&1 | tee output.log; mkdir -p results/$settings/$run/$ds/ && mv trajectory.csv results/$settings/$run/$ds/tracking.csv && mv output.log *.json results/$settings/$run/$ds/
export ds=MOO05    dsname=MOO05_inspect_easy_$settings      calib=data/msd/msdmo_calib.json           config=data/msd/msdmo_config_vo$confext.json
echo ">>> [$settings - $run - $ds]" && time ./build/basalt_vio --show-gui 0 --deterministic 1 --use-imu 0 --use-mvs $usemv --dataset-path $dspath/$dsname  --dataset-type euroc --cam-calib $calib --config-path $config --save-trajectory euroc 2>&1 | tee output.log; mkdir -p results/$settings/$run/$ds/ && mv trajectory.csv results/$settings/$run/$ds/tracking.csv && mv output.log *.json results/$settings/$run/$ds/
export ds=MOO07    dsname=MOO07_mapping_easy_$settings      calib=data/msd/msdmo_calib.json           config=data/msd/msdmo_config_vo$confext.json
echo ">>> [$settings - $run - $ds]" && time ./build/basalt_vio --show-gui 0 --deterministic 1 --use-imu 0 --use-mvs $usemv --dataset-path $dspath/$dsname  --dataset-type euroc --cam-calib $calib --config-path $config --save-trajectory euroc 2>&1 | tee output.log; mkdir -p results/$settings/$run/$ds/ && mv trajectory.csv results/$settings/$run/$ds/tracking.csv && mv output.log *.json results/$settings/$run/$ds/
export ds=TR2      dsname=dataset-room2_512_16_$settings    calib=data/tum/tumvi_512_ds_calib.json    config=data/tum/tumvi_512_config_vo$confext.json
echo ">>> [$settings - $run - $ds]" && time ./build/basalt_vio --show-gui 0 --deterministic 1 --use-imu 0 --use-mvs $usemv --dataset-path $dspath/$dsname  --dataset-type euroc --cam-calib $calib --config-path $config --save-trajectory euroc 2>&1 | tee output.log; mkdir -p results/$settings/$run/$ds/ && mv trajectory.csv results/$settings/$run/$ds/tracking.csv && mv output.log *.json results/$settings/$run/$ds/
export ds=TR4      dsname=dataset-room4_512_16_$settings    calib=data/tum/tumvi_512_ds_calib.json    config=data/tum/tumvi_512_config_vo$confext.json
echo ">>> [$settings - $run - $ds]" && time ./build/basalt_vio --show-gui 0 --deterministic 1 --use-imu 0 --use-mvs $usemv --dataset-path $dspath/$dsname  --dataset-type euroc --cam-calib $calib --config-path $config --save-trajectory euroc 2>&1 | tee output.log; mkdir -p results/$settings/$run/$ds/ && mv trajectory.csv results/$settings/$run/$ds/tracking.csv && mv output.log *.json results/$settings/$run/$ds/
export ds=TR6      dsname=dataset-room6_512_16_$settings    calib=data/tum/tumvi_512_ds_calib.json    config=data/tum/tumvi_512_config_vo$confext.json
echo ">>> [$settings - $run - $ds]" && time ./build/basalt_vio --show-gui 0 --deterministic 1 --use-imu 0 --use-mvs $usemv --dataset-path $dspath/$dsname  --dataset-type euroc --cam-calib $calib --config-path $config --save-trajectory euroc 2>&1 | tee output.log; mkdir -p results/$settings/$run/$ds/ && mv trajectory.csv results/$settings/$run/$ds/tracking.csv && mv output.log *.json results/$settings/$run/$ds/

export run=mvof usemv=1 confext=".mvof"
export ds=EMH01    dsname=MH_01_easy_$settings              calib=data/euroc/euroc_ds_calib.json      config=data/euroc/euroc_config_vo$confext.json
echo ">>> [$settings - $run - $ds]" && time ./build/basalt_vio --show-gui 0 --deterministic 1 --use-imu 0 --use-mvs $usemv --dataset-path $dspath/$dsname  --dataset-type euroc --cam-calib $calib --config-path $config --save-trajectory euroc 2>&1 | tee output.log; mkdir -p results/$settings/$run/$ds/ && mv trajectory.csv results/$settings/$run/$ds/tracking.csv && mv output.log *.json results/$settings/$run/$ds/
export ds=EMH02    dsname=MH_02_easy_$settings              calib=data/euroc/euroc_ds_calib.json      config=data/euroc/euroc_config_vo$confext.json
echo ">>> [$settings - $run - $ds]" && time ./build/basalt_vio --show-gui 0 --deterministic 1 --use-imu 0 --use-mvs $usemv --dataset-path $dspath/$dsname  --dataset-type euroc --cam-calib $calib --config-path $config --save-trajectory euroc 2>&1 | tee output.log; mkdir -p results/$settings/$run/$ds/ && mv trajectory.csv results/$settings/$run/$ds/tracking.csv && mv output.log *.json results/$settings/$run/$ds/
export ds=EV101    dsname=V1_01_easy_$settings              calib=data/euroc/euroc_ds_calib.json      config=data/euroc/euroc_config_vo$confext.json
echo ">>> [$settings - $run - $ds]" && time ./build/basalt_vio --show-gui 0 --deterministic 1 --use-imu 0 --use-mvs $usemv --dataset-path $dspath/$dsname  --dataset-type euroc --cam-calib $calib --config-path $config --save-trajectory euroc 2>&1 | tee output.log; mkdir -p results/$settings/$run/$ds/ && mv trajectory.csv results/$settings/$run/$ds/tracking.csv && mv output.log *.json results/$settings/$run/$ds/
export ds=EV201    dsname=V2_01_easy_$settings              calib=data/euroc/euroc_ds_calib.json      config=data/euroc/euroc_config_vo$confext.json
echo ">>> [$settings - $run - $ds]" && time ./build/basalt_vio --show-gui 0 --deterministic 1 --use-imu 0 --use-mvs $usemv --dataset-path $dspath/$dsname  --dataset-type euroc --cam-calib $calib --config-path $config --save-trajectory euroc 2>&1 | tee output.log; mkdir -p results/$settings/$run/$ds/ && mv trajectory.csv results/$settings/$run/$ds/tracking.csv && mv output.log *.json results/$settings/$run/$ds/
export ds=MGO05    dsname=MGO05_inspect_easy_$settings      calib=data/msd/msdmg_calib.json           config=data/msd/msdmg_config_vo$confext.json
echo ">>> [$settings - $run - $ds]" && time ./build/basalt_vio --show-gui 0 --deterministic 1 --use-imu 0 --use-mvs $usemv --dataset-path $dspath/$dsname  --dataset-type euroc --cam-calib $calib --config-path $config --save-trajectory euroc 2>&1 | tee output.log; mkdir -p results/$settings/$run/$ds/ && mv trajectory.csv results/$settings/$run/$ds/tracking.csv && mv output.log *.json results/$settings/$run/$ds/
export ds=MGO07    dsname=MGO07_mapping_easy_$settings      calib=data/msd/msdmg_calib.json           config=data/msd/msdmg_config_vo$confext.json
echo ">>> [$settings - $run - $ds]" && time ./build/basalt_vio --show-gui 0 --deterministic 1 --use-imu 0 --use-mvs $usemv --dataset-path $dspath/$dsname  --dataset-type euroc --cam-calib $calib --config-path $config --save-trajectory euroc 2>&1 | tee output.log; mkdir -p results/$settings/$run/$ds/ && mv trajectory.csv results/$settings/$run/$ds/tracking.csv && mv output.log *.json results/$settings/$run/$ds/
export ds=MIO05    dsname=MIO05_inspect_easy_$settings      calib=data/msd/msdmi_calib.json           config=data/msd/msdmi_config_vo$confext.json
echo ">>> [$settings - $run - $ds]" && time ./build/basalt_vio --show-gui 0 --deterministic 1 --use-imu 0 --use-mvs $usemv --dataset-path $dspath/$dsname  --dataset-type euroc --cam-calib $calib --config-path $config --save-trajectory euroc 2>&1 | tee output.log; mkdir -p results/$settings/$run/$ds/ && mv trajectory.csv results/$settings/$run/$ds/tracking.csv && mv output.log *.json results/$settings/$run/$ds/
export ds=MIO07    dsname=MIO07_mapping_easy_$settings      calib=data/msd/msdmi_calib.json           config=data/msd/msdmi_config_vo$confext.json
echo ">>> [$settings - $run - $ds]" && time ./build/basalt_vio --show-gui 0 --deterministic 1 --use-imu 0 --use-mvs $usemv --dataset-path $dspath/$dsname  --dataset-type euroc --cam-calib $calib --config-path $config --save-trajectory euroc 2>&1 | tee output.log; mkdir -p results/$settings/$run/$ds/ && mv trajectory.csv results/$settings/$run/$ds/tracking.csv && mv output.log *.json results/$settings/$run/$ds/
export ds=MOO05    dsname=MOO05_inspect_easy_$settings      calib=data/msd/msdmo_calib.json           config=data/msd/msdmo_config_vo$confext.json
echo ">>> [$settings - $run - $ds]" && time ./build/basalt_vio --show-gui 0 --deterministic 1 --use-imu 0 --use-mvs $usemv --dataset-path $dspath/$dsname  --dataset-type euroc --cam-calib $calib --config-path $config --save-trajectory euroc 2>&1 | tee output.log; mkdir -p results/$settings/$run/$ds/ && mv trajectory.csv results/$settings/$run/$ds/tracking.csv && mv output.log *.json results/$settings/$run/$ds/
export ds=MOO07    dsname=MOO07_mapping_easy_$settings      calib=data/msd/msdmo_calib.json           config=data/msd/msdmo_config_vo$confext.json
echo ">>> [$settings - $run - $ds]" && time ./build/basalt_vio --show-gui 0 --deterministic 1 --use-imu 0 --use-mvs $usemv --dataset-path $dspath/$dsname  --dataset-type euroc --cam-calib $calib --config-path $config --save-trajectory euroc 2>&1 | tee output.log; mkdir -p results/$settings/$run/$ds/ && mv trajectory.csv results/$settings/$run/$ds/tracking.csv && mv output.log *.json results/$settings/$run/$ds/
export ds=TR2      dsname=dataset-room2_512_16_$settings    calib=data/tum/tumvi_512_ds_calib.json    config=data/tum/tumvi_512_config_vo$confext.json
echo ">>> [$settings - $run - $ds]" && time ./build/basalt_vio --show-gui 0 --deterministic 1 --use-imu 0 --use-mvs $usemv --dataset-path $dspath/$dsname  --dataset-type euroc --cam-calib $calib --config-path $config --save-trajectory euroc 2>&1 | tee output.log; mkdir -p results/$settings/$run/$ds/ && mv trajectory.csv results/$settings/$run/$ds/tracking.csv && mv output.log *.json results/$settings/$run/$ds/
export ds=TR4      dsname=dataset-room4_512_16_$settings    calib=data/tum/tumvi_512_ds_calib.json    config=data/tum/tumvi_512_config_vo$confext.json
echo ">>> [$settings - $run - $ds]" && time ./build/basalt_vio --show-gui 0 --deterministic 1 --use-imu 0 --use-mvs $usemv --dataset-path $dspath/$dsname  --dataset-type euroc --cam-calib $calib --config-path $config --save-trajectory euroc 2>&1 | tee output.log; mkdir -p results/$settings/$run/$ds/ && mv trajectory.csv results/$settings/$run/$ds/tracking.csv && mv output.log *.json results/$settings/$run/$ds/
export ds=TR6      dsname=dataset-room6_512_16_$settings    calib=data/tum/tumvi_512_ds_calib.json    config=data/tum/tumvi_512_config_vo$confext.json
echo ">>> [$settings - $run - $ds]" && time ./build/basalt_vio --show-gui 0 --deterministic 1 --use-imu 0 --use-mvs $usemv --dataset-path $dspath/$dsname  --dataset-type euroc --cam-calib $calib --config-path $config --save-trajectory euroc 2>&1 | tee output.log; mkdir -p results/$settings/$run/$ds/ && mv trajectory.csv results/$settings/$run/$ds/tracking.csv && mv output.log *.json results/$settings/$run/$ds/

export run=of usemv=0 confext=".ofmv"
export ds=EMH01    dsname=MH_01_easy_$settings              calib=data/euroc/euroc_ds_calib.json      config=data/euroc/euroc_config_vo$confext.json
echo ">>> [$settings - $run - $ds]" && time ./build/basalt_vio --show-gui 0 --deterministic 1 --use-imu 0 --use-mvs $usemv --dataset-path $dspath/$dsname  --dataset-type euroc --cam-calib $calib --config-path $config --save-trajectory euroc 2>&1 | tee output.log; mkdir -p results/$settings/$run/$ds/ && mv trajectory.csv results/$settings/$run/$ds/tracking.csv && mv output.log *.json results/$settings/$run/$ds/
export ds=EMH02    dsname=MH_02_easy_$settings              calib=data/euroc/euroc_ds_calib.json      config=data/euroc/euroc_config_vo$confext.json
echo ">>> [$settings - $run - $ds]" && time ./build/basalt_vio --show-gui 0 --deterministic 1 --use-imu 0 --use-mvs $usemv --dataset-path $dspath/$dsname  --dataset-type euroc --cam-calib $calib --config-path $config --save-trajectory euroc 2>&1 | tee output.log; mkdir -p results/$settings/$run/$ds/ && mv trajectory.csv results/$settings/$run/$ds/tracking.csv && mv output.log *.json results/$settings/$run/$ds/
export ds=EV101    dsname=V1_01_easy_$settings              calib=data/euroc/euroc_ds_calib.json      config=data/euroc/euroc_config_vo$confext.json
echo ">>> [$settings - $run - $ds]" && time ./build/basalt_vio --show-gui 0 --deterministic 1 --use-imu 0 --use-mvs $usemv --dataset-path $dspath/$dsname  --dataset-type euroc --cam-calib $calib --config-path $config --save-trajectory euroc 2>&1 | tee output.log; mkdir -p results/$settings/$run/$ds/ && mv trajectory.csv results/$settings/$run/$ds/tracking.csv && mv output.log *.json results/$settings/$run/$ds/
export ds=EV201    dsname=V2_01_easy_$settings              calib=data/euroc/euroc_ds_calib.json      config=data/euroc/euroc_config_vo$confext.json
echo ">>> [$settings - $run - $ds]" && time ./build/basalt_vio --show-gui 0 --deterministic 1 --use-imu 0 --use-mvs $usemv --dataset-path $dspath/$dsname  --dataset-type euroc --cam-calib $calib --config-path $config --save-trajectory euroc 2>&1 | tee output.log; mkdir -p results/$settings/$run/$ds/ && mv trajectory.csv results/$settings/$run/$ds/tracking.csv && mv output.log *.json results/$settings/$run/$ds/
export ds=MGO05    dsname=MGO05_inspect_easy_$settings      calib=data/msd/msdmg_calib.json           config=data/msd/msdmg_config_vo$confext.json
echo ">>> [$settings - $run - $ds]" && time ./build/basalt_vio --show-gui 0 --deterministic 1 --use-imu 0 --use-mvs $usemv --dataset-path $dspath/$dsname  --dataset-type euroc --cam-calib $calib --config-path $config --save-trajectory euroc 2>&1 | tee output.log; mkdir -p results/$settings/$run/$ds/ && mv trajectory.csv results/$settings/$run/$ds/tracking.csv && mv output.log *.json results/$settings/$run/$ds/
export ds=MGO07    dsname=MGO07_mapping_easy_$settings      calib=data/msd/msdmg_calib.json           config=data/msd/msdmg_config_vo$confext.json
echo ">>> [$settings - $run - $ds]" && time ./build/basalt_vio --show-gui 0 --deterministic 1 --use-imu 0 --use-mvs $usemv --dataset-path $dspath/$dsname  --dataset-type euroc --cam-calib $calib --config-path $config --save-trajectory euroc 2>&1 | tee output.log; mkdir -p results/$settings/$run/$ds/ && mv trajectory.csv results/$settings/$run/$ds/tracking.csv && mv output.log *.json results/$settings/$run/$ds/
export ds=MIO05    dsname=MIO05_inspect_easy_$settings      calib=data/msd/msdmi_calib.json           config=data/msd/msdmi_config_vo$confext.json
echo ">>> [$settings - $run - $ds]" && time ./build/basalt_vio --show-gui 0 --deterministic 1 --use-imu 0 --use-mvs $usemv --dataset-path $dspath/$dsname  --dataset-type euroc --cam-calib $calib --config-path $config --save-trajectory euroc 2>&1 | tee output.log; mkdir -p results/$settings/$run/$ds/ && mv trajectory.csv results/$settings/$run/$ds/tracking.csv && mv output.log *.json results/$settings/$run/$ds/
export ds=MIO07    dsname=MIO07_mapping_easy_$settings      calib=data/msd/msdmi_calib.json           config=data/msd/msdmi_config_vo$confext.json
echo ">>> [$settings - $run - $ds]" && time ./build/basalt_vio --show-gui 0 --deterministic 1 --use-imu 0 --use-mvs $usemv --dataset-path $dspath/$dsname  --dataset-type euroc --cam-calib $calib --config-path $config --save-trajectory euroc 2>&1 | tee output.log; mkdir -p results/$settings/$run/$ds/ && mv trajectory.csv results/$settings/$run/$ds/tracking.csv && mv output.log *.json results/$settings/$run/$ds/
export ds=MOO05    dsname=MOO05_inspect_easy_$settings      calib=data/msd/msdmo_calib.json           config=data/msd/msdmo_config_vo$confext.json
echo ">>> [$settings - $run - $ds]" && time ./build/basalt_vio --show-gui 0 --deterministic 1 --use-imu 0 --use-mvs $usemv --dataset-path $dspath/$dsname  --dataset-type euroc --cam-calib $calib --config-path $config --save-trajectory euroc 2>&1 | tee output.log; mkdir -p results/$settings/$run/$ds/ && mv trajectory.csv results/$settings/$run/$ds/tracking.csv && mv output.log *.json results/$settings/$run/$ds/
export ds=MOO07    dsname=MOO07_mapping_easy_$settings      calib=data/msd/msdmo_calib.json           config=data/msd/msdmo_config_vo$confext.json
echo ">>> [$settings - $run - $ds]" && time ./build/basalt_vio --show-gui 0 --deterministic 1 --use-imu 0 --use-mvs $usemv --dataset-path $dspath/$dsname  --dataset-type euroc --cam-calib $calib --config-path $config --save-trajectory euroc 2>&1 | tee output.log; mkdir -p results/$settings/$run/$ds/ && mv trajectory.csv results/$settings/$run/$ds/tracking.csv && mv output.log *.json results/$settings/$run/$ds/
export ds=TR2      dsname=dataset-room2_512_16_$settings    calib=data/tum/tumvi_512_ds_calib.json    config=data/tum/tumvi_512_config_vo$confext.json
echo ">>> [$settings - $run - $ds]" && time ./build/basalt_vio --show-gui 0 --deterministic 1 --use-imu 0 --use-mvs $usemv --dataset-path $dspath/$dsname  --dataset-type euroc --cam-calib $calib --config-path $config --save-trajectory euroc 2>&1 | tee output.log; mkdir -p results/$settings/$run/$ds/ && mv trajectory.csv results/$settings/$run/$ds/tracking.csv && mv output.log *.json results/$settings/$run/$ds/
export ds=TR4      dsname=dataset-room4_512_16_$settings    calib=data/tum/tumvi_512_ds_calib.json    config=data/tum/tumvi_512_config_vo$confext.json
echo ">>> [$settings - $run - $ds]" && time ./build/basalt_vio --show-gui 0 --deterministic 1 --use-imu 0 --use-mvs $usemv --dataset-path $dspath/$dsname  --dataset-type euroc --cam-calib $calib --config-path $config --save-trajectory euroc 2>&1 | tee output.log; mkdir -p results/$settings/$run/$ds/ && mv trajectory.csv results/$settings/$run/$ds/tracking.csv && mv output.log *.json results/$settings/$run/$ds/
export ds=TR6      dsname=dataset-room6_512_16_$settings    calib=data/tum/tumvi_512_ds_calib.json    config=data/tum/tumvi_512_config_vo$confext.json
echo ">>> [$settings - $run - $ds]" && time ./build/basalt_vio --show-gui 0 --deterministic 1 --use-imu 0 --use-mvs $usemv --dataset-path $dspath/$dsname  --dataset-type euroc --cam-calib $calib --config-path $config --save-trajectory euroc 2>&1 | tee output.log; mkdir -p results/$settings/$run/$ds/ && mv trajectory.csv results/$settings/$run/$ds/tracking.csv && mv output.log *.json results/$settings/$run/$ds/

source $xrtmet/.venv/bin/activate
$xrtmet/batch.py results/$settings/ $xrtmet/test/data/targets --metrics success ate rte --verbose --save_file batch_$settings.json
