export run=ofmv usemv=1 confext=""
export ds=EMH01    dspath=MH_01_easy              calib=data/euroc/euroc_ds_calib.json      config=data/euroc/euroc_config_vo$confext.json
echo ">>> [$run - $ds]" && time ./build/basalt_vio --show-gui 0 --deterministic 1 --use-imu 0 --use-mvs $usemv --dataset-path ds/$dspath  --dataset-type euroc --cam-calib $calib --config-path $config --save-trajectory euroc 2>&1 | tee output.log; mkdir -p results/$run/$ds/ && mv trajectory.csv results/$run/$ds/tracking.csv && mv output.log *.json results/$run/$ds/
export ds=EMH02    dspath=MH_02_easy              calib=data/euroc/euroc_ds_calib.json      config=data/euroc/euroc_config_vo$confext.json
echo ">>> [$run - $ds]" && time ./build/basalt_vio --show-gui 0 --deterministic 1 --use-imu 0 --use-mvs $usemv --dataset-path ds/$dspath  --dataset-type euroc --cam-calib $calib --config-path $config --save-trajectory euroc 2>&1 | tee output.log; mkdir -p results/$run/$ds/ && mv trajectory.csv results/$run/$ds/tracking.csv && mv output.log *.json results/$run/$ds/
export ds=EMH03    dspath=MH_03_medium            calib=data/euroc/euroc_ds_calib.json      config=data/euroc/euroc_config_vo$confext.json
echo ">>> [$run - $ds]" && time ./build/basalt_vio --show-gui 0 --deterministic 1 --use-imu 0 --use-mvs $usemv --dataset-path ds/$dspath  --dataset-type euroc --cam-calib $calib --config-path $config --save-trajectory euroc 2>&1 | tee output.log; mkdir -p results/$run/$ds/ && mv trajectory.csv results/$run/$ds/tracking.csv && mv output.log *.json results/$run/$ds/
export ds=EMH04    dspath=MH_04_difficult         calib=data/euroc/euroc_ds_calib.json      config=data/euroc/euroc_config_vo$confext.json
echo ">>> [$run - $ds]" && time ./build/basalt_vio --show-gui 0 --deterministic 1 --use-imu 0 --use-mvs $usemv --dataset-path ds/$dspath  --dataset-type euroc --cam-calib $calib --config-path $config --save-trajectory euroc 2>&1 | tee output.log; mkdir -p results/$run/$ds/ && mv trajectory.csv results/$run/$ds/tracking.csv && mv output.log *.json results/$run/$ds/
export ds=EMH05    dspath=MH_05_difficult         calib=data/euroc/euroc_ds_calib.json      config=data/euroc/euroc_config_vo$confext.json
echo ">>> [$run - $ds]" && time ./build/basalt_vio --show-gui 0 --deterministic 1 --use-imu 0 --use-mvs $usemv --dataset-path ds/$dspath  --dataset-type euroc --cam-calib $calib --config-path $config --save-trajectory euroc 2>&1 | tee output.log; mkdir -p results/$run/$ds/ && mv trajectory.csv results/$run/$ds/tracking.csv && mv output.log *.json results/$run/$ds/
export ds=EV101    dspath=V1_01_easy              calib=data/euroc/euroc_ds_calib.json      config=data/euroc/euroc_config_vo$confext.json
echo ">>> [$run - $ds]" && time ./build/basalt_vio --show-gui 0 --deterministic 1 --use-imu 0 --use-mvs $usemv --dataset-path ds/$dspath  --dataset-type euroc --cam-calib $calib --config-path $config --save-trajectory euroc 2>&1 | tee output.log; mkdir -p results/$run/$ds/ && mv trajectory.csv results/$run/$ds/tracking.csv && mv output.log *.json results/$run/$ds/
export ds=EV102    dspath=V1_02_medium            calib=data/euroc/euroc_ds_calib.json      config=data/euroc/euroc_config_vo$confext.json
echo ">>> [$run - $ds]" && time ./build/basalt_vio --show-gui 0 --deterministic 1 --use-imu 0 --use-mvs $usemv --dataset-path ds/$dspath  --dataset-type euroc --cam-calib $calib --config-path $config --save-trajectory euroc 2>&1 | tee output.log; mkdir -p results/$run/$ds/ && mv trajectory.csv results/$run/$ds/tracking.csv && mv output.log *.json results/$run/$ds/
export ds=EV201    dspath=V2_01_easy              calib=data/euroc/euroc_ds_calib.json      config=data/euroc/euroc_config_vo$confext.json
echo ">>> [$run - $ds]" && time ./build/basalt_vio --show-gui 0 --deterministic 1 --use-imu 0 --use-mvs $usemv --dataset-path ds/$dspath  --dataset-type euroc --cam-calib $calib --config-path $config --save-trajectory euroc 2>&1 | tee output.log; mkdir -p results/$run/$ds/ && mv trajectory.csv results/$run/$ds/tracking.csv && mv output.log *.json results/$run/$ds/
export ds=MGO05    dspath=MGO05_inspect_easy      calib=data/msd/msdmg_calib.json           config=data/msd/msdmg_config_vo$confext.json
echo ">>> [$run - $ds]" && time ./build/basalt_vio --show-gui 0 --deterministic 1 --use-imu 0 --use-mvs $usemv --dataset-path ds/$dspath  --dataset-type euroc --cam-calib $calib --config-path $config --save-trajectory euroc 2>&1 | tee output.log; mkdir -p results/$run/$ds/ && mv trajectory.csv results/$run/$ds/tracking.csv && mv output.log *.json results/$run/$ds/
export ds=MGO07    dspath=MGO07_mapping_easy      calib=data/msd/msdmg_calib.json           config=data/msd/msdmg_config_vo$confext.json
echo ">>> [$run - $ds]" && time ./build/basalt_vio --show-gui 0 --deterministic 1 --use-imu 0 --use-mvs $usemv --dataset-path ds/$dspath  --dataset-type euroc --cam-calib $calib --config-path $config --save-trajectory euroc 2>&1 | tee output.log; mkdir -p results/$run/$ds/ && mv trajectory.csv results/$run/$ds/tracking.csv && mv output.log *.json results/$run/$ds/
export ds=MIO05    dspath=MIO05_inspect_easy      calib=data/msd/msdmi_calib.json           config=data/msd/msdmi_config_vo$confext.json
echo ">>> [$run - $ds]" && time ./build/basalt_vio --show-gui 0 --deterministic 1 --use-imu 0 --use-mvs $usemv --dataset-path ds/$dspath  --dataset-type euroc --cam-calib $calib --config-path $config --save-trajectory euroc 2>&1 | tee output.log; mkdir -p results/$run/$ds/ && mv trajectory.csv results/$run/$ds/tracking.csv && mv output.log *.json results/$run/$ds/
export ds=MIO07    dspath=MIO07_mapping_easy      calib=data/msd/msdmi_calib.json           config=data/msd/msdmi_config_vo$confext.json
echo ">>> [$run - $ds]" && time ./build/basalt_vio --show-gui 0 --deterministic 1 --use-imu 0 --use-mvs $usemv --dataset-path ds/$dspath  --dataset-type euroc --cam-calib $calib --config-path $config --save-trajectory euroc 2>&1 | tee output.log; mkdir -p results/$run/$ds/ && mv trajectory.csv results/$run/$ds/tracking.csv && mv output.log *.json results/$run/$ds/
export ds=MOO05    dspath=MOO05_inspect_easy      calib=data/msd/msdmo_calib.json           config=data/msd/msdmo_config_vo$confext.json
echo ">>> [$run - $ds]" && time ./build/basalt_vio --show-gui 0 --deterministic 1 --use-imu 0 --use-mvs $usemv --dataset-path ds/$dspath  --dataset-type euroc --cam-calib $calib --config-path $config --save-trajectory euroc 2>&1 | tee output.log; mkdir -p results/$run/$ds/ && mv trajectory.csv results/$run/$ds/tracking.csv && mv output.log *.json results/$run/$ds/
export ds=MOO07    dspath=MOO07_mapping_easy      calib=data/msd/msdmo_calib.json           config=data/msd/msdmo_config_vo$confext.json
echo ">>> [$run - $ds]" && time ./build/basalt_vio --show-gui 0 --deterministic 1 --use-imu 0 --use-mvs $usemv --dataset-path ds/$dspath  --dataset-type euroc --cam-calib $calib --config-path $config --save-trajectory euroc 2>&1 | tee output.log; mkdir -p results/$run/$ds/ && mv trajectory.csv results/$run/$ds/tracking.csv && mv output.log *.json results/$run/$ds/
export ds=TR1      dspath=dataset-room1_512_16    calib=data/tum/tumvi_512_ds_calib.json    config=data/tum/tumvi_512_config_vo$confext.json
echo ">>> [$run - $ds]" && time ./build/basalt_vio --show-gui 0 --deterministic 1 --use-imu 0 --use-mvs $usemv --dataset-path ds/$dspath  --dataset-type euroc --cam-calib $calib --config-path $config --save-trajectory euroc 2>&1 | tee output.log; mkdir -p results/$run/$ds/ && mv trajectory.csv results/$run/$ds/tracking.csv && mv output.log *.json results/$run/$ds/
export ds=TR2      dspath=dataset-room2_512_16    calib=data/tum/tumvi_512_ds_calib.json    config=data/tum/tumvi_512_config_vo$confext.json
echo ">>> [$run - $ds]" && time ./build/basalt_vio --show-gui 0 --deterministic 1 --use-imu 0 --use-mvs $usemv --dataset-path ds/$dspath  --dataset-type euroc --cam-calib $calib --config-path $config --save-trajectory euroc 2>&1 | tee output.log; mkdir -p results/$run/$ds/ && mv trajectory.csv results/$run/$ds/tracking.csv && mv output.log *.json results/$run/$ds/
export ds=TR3      dspath=dataset-room3_512_16    calib=data/tum/tumvi_512_ds_calib.json    config=data/tum/tumvi_512_config_vo$confext.json
echo ">>> [$run - $ds]" && time ./build/basalt_vio --show-gui 0 --deterministic 1 --use-imu 0 --use-mvs $usemv --dataset-path ds/$dspath  --dataset-type euroc --cam-calib $calib --config-path $config --save-trajectory euroc 2>&1 | tee output.log; mkdir -p results/$run/$ds/ && mv trajectory.csv results/$run/$ds/tracking.csv && mv output.log *.json results/$run/$ds/
export ds=TR4      dspath=dataset-room4_512_16    calib=data/tum/tumvi_512_ds_calib.json    config=data/tum/tumvi_512_config_vo$confext.json
echo ">>> [$run - $ds]" && time ./build/basalt_vio --show-gui 0 --deterministic 1 --use-imu 0 --use-mvs $usemv --dataset-path ds/$dspath  --dataset-type euroc --cam-calib $calib --config-path $config --save-trajectory euroc 2>&1 | tee output.log; mkdir -p results/$run/$ds/ && mv trajectory.csv results/$run/$ds/tracking.csv && mv output.log *.json results/$run/$ds/
export ds=TR5      dspath=dataset-room5_512_16    calib=data/tum/tumvi_512_ds_calib.json    config=data/tum/tumvi_512_config_vo$confext.json
echo ">>> [$run - $ds]" && time ./build/basalt_vio --show-gui 0 --deterministic 1 --use-imu 0 --use-mvs $usemv --dataset-path ds/$dspath  --dataset-type euroc --cam-calib $calib --config-path $config --save-trajectory euroc 2>&1 | tee output.log; mkdir -p results/$run/$ds/ && mv trajectory.csv results/$run/$ds/tracking.csv && mv output.log *.json results/$run/$ds/
export ds=TR6      dspath=dataset-room6_512_16    calib=data/tum/tumvi_512_ds_calib.json    config=data/tum/tumvi_512_config_vo$confext.json
echo ">>> [$run - $ds]" && time ./build/basalt_vio --show-gui 0 --deterministic 1 --use-imu 0 --use-mvs $usemv --dataset-path ds/$dspath  --dataset-type euroc --cam-calib $calib --config-path $config --save-trajectory euroc 2>&1 | tee output.log; mkdir -p results/$run/$ds/ && mv trajectory.csv results/$run/$ds/tracking.csv && mv output.log *.json results/$run/$ds/

export run=mvof usemv=1 confext=".mvof"
export ds=EMH01    dspath=MH_01_easy              calib=data/euroc/euroc_ds_calib.json      config=data/euroc/euroc_config_vo$confext.json
echo ">>> [$run - $ds]" && time ./build/basalt_vio --show-gui 0 --deterministic 1 --use-imu 0 --use-mvs $usemv --dataset-path ds/$dspath  --dataset-type euroc --cam-calib $calib --config-path $config --save-trajectory euroc 2>&1 | tee output.log; mkdir -p results/$run/$ds/ && mv trajectory.csv results/$run/$ds/tracking.csv && mv output.log *.json results/$run/$ds/
export ds=EMH02    dspath=MH_02_easy              calib=data/euroc/euroc_ds_calib.json      config=data/euroc/euroc_config_vo$confext.json
echo ">>> [$run - $ds]" && time ./build/basalt_vio --show-gui 0 --deterministic 1 --use-imu 0 --use-mvs $usemv --dataset-path ds/$dspath  --dataset-type euroc --cam-calib $calib --config-path $config --save-trajectory euroc 2>&1 | tee output.log; mkdir -p results/$run/$ds/ && mv trajectory.csv results/$run/$ds/tracking.csv && mv output.log *.json results/$run/$ds/
export ds=EMH03    dspath=MH_03_medium            calib=data/euroc/euroc_ds_calib.json      config=data/euroc/euroc_config_vo$confext.json
echo ">>> [$run - $ds]" && time ./build/basalt_vio --show-gui 0 --deterministic 1 --use-imu 0 --use-mvs $usemv --dataset-path ds/$dspath  --dataset-type euroc --cam-calib $calib --config-path $config --save-trajectory euroc 2>&1 | tee output.log; mkdir -p results/$run/$ds/ && mv trajectory.csv results/$run/$ds/tracking.csv && mv output.log *.json results/$run/$ds/
export ds=EMH04    dspath=MH_04_difficult         calib=data/euroc/euroc_ds_calib.json      config=data/euroc/euroc_config_vo$confext.json
echo ">>> [$run - $ds]" && time ./build/basalt_vio --show-gui 0 --deterministic 1 --use-imu 0 --use-mvs $usemv --dataset-path ds/$dspath  --dataset-type euroc --cam-calib $calib --config-path $config --save-trajectory euroc 2>&1 | tee output.log; mkdir -p results/$run/$ds/ && mv trajectory.csv results/$run/$ds/tracking.csv && mv output.log *.json results/$run/$ds/
export ds=EMH05    dspath=MH_05_difficult         calib=data/euroc/euroc_ds_calib.json      config=data/euroc/euroc_config_vo$confext.json
echo ">>> [$run - $ds]" && time ./build/basalt_vio --show-gui 0 --deterministic 1 --use-imu 0 --use-mvs $usemv --dataset-path ds/$dspath  --dataset-type euroc --cam-calib $calib --config-path $config --save-trajectory euroc 2>&1 | tee output.log; mkdir -p results/$run/$ds/ && mv trajectory.csv results/$run/$ds/tracking.csv && mv output.log *.json results/$run/$ds/
export ds=EV101    dspath=V1_01_easy              calib=data/euroc/euroc_ds_calib.json      config=data/euroc/euroc_config_vo$confext.json
echo ">>> [$run - $ds]" && time ./build/basalt_vio --show-gui 0 --deterministic 1 --use-imu 0 --use-mvs $usemv --dataset-path ds/$dspath  --dataset-type euroc --cam-calib $calib --config-path $config --save-trajectory euroc 2>&1 | tee output.log; mkdir -p results/$run/$ds/ && mv trajectory.csv results/$run/$ds/tracking.csv && mv output.log *.json results/$run/$ds/
export ds=EV102    dspath=V1_02_medium            calib=data/euroc/euroc_ds_calib.json      config=data/euroc/euroc_config_vo$confext.json
echo ">>> [$run - $ds]" && time ./build/basalt_vio --show-gui 0 --deterministic 1 --use-imu 0 --use-mvs $usemv --dataset-path ds/$dspath  --dataset-type euroc --cam-calib $calib --config-path $config --save-trajectory euroc 2>&1 | tee output.log; mkdir -p results/$run/$ds/ && mv trajectory.csv results/$run/$ds/tracking.csv && mv output.log *.json results/$run/$ds/
export ds=EV201    dspath=V2_01_easy              calib=data/euroc/euroc_ds_calib.json      config=data/euroc/euroc_config_vo$confext.json
echo ">>> [$run - $ds]" && time ./build/basalt_vio --show-gui 0 --deterministic 1 --use-imu 0 --use-mvs $usemv --dataset-path ds/$dspath  --dataset-type euroc --cam-calib $calib --config-path $config --save-trajectory euroc 2>&1 | tee output.log; mkdir -p results/$run/$ds/ && mv trajectory.csv results/$run/$ds/tracking.csv && mv output.log *.json results/$run/$ds/
export ds=MGO05    dspath=MGO05_inspect_easy      calib=data/msd/msdmg_calib.json           config=data/msd/msdmg_config_vo$confext.json
echo ">>> [$run - $ds]" && time ./build/basalt_vio --show-gui 0 --deterministic 1 --use-imu 0 --use-mvs $usemv --dataset-path ds/$dspath  --dataset-type euroc --cam-calib $calib --config-path $config --save-trajectory euroc 2>&1 | tee output.log; mkdir -p results/$run/$ds/ && mv trajectory.csv results/$run/$ds/tracking.csv && mv output.log *.json results/$run/$ds/
export ds=MGO07    dspath=MGO07_mapping_easy      calib=data/msd/msdmg_calib.json           config=data/msd/msdmg_config_vo$confext.json
echo ">>> [$run - $ds]" && time ./build/basalt_vio --show-gui 0 --deterministic 1 --use-imu 0 --use-mvs $usemv --dataset-path ds/$dspath  --dataset-type euroc --cam-calib $calib --config-path $config --save-trajectory euroc 2>&1 | tee output.log; mkdir -p results/$run/$ds/ && mv trajectory.csv results/$run/$ds/tracking.csv && mv output.log *.json results/$run/$ds/
export ds=MIO05    dspath=MIO05_inspect_easy      calib=data/msd/msdmi_calib.json           config=data/msd/msdmi_config_vo$confext.json
echo ">>> [$run - $ds]" && time ./build/basalt_vio --show-gui 0 --deterministic 1 --use-imu 0 --use-mvs $usemv --dataset-path ds/$dspath  --dataset-type euroc --cam-calib $calib --config-path $config --save-trajectory euroc 2>&1 | tee output.log; mkdir -p results/$run/$ds/ && mv trajectory.csv results/$run/$ds/tracking.csv && mv output.log *.json results/$run/$ds/
export ds=MIO07    dspath=MIO07_mapping_easy      calib=data/msd/msdmi_calib.json           config=data/msd/msdmi_config_vo$confext.json
echo ">>> [$run - $ds]" && time ./build/basalt_vio --show-gui 0 --deterministic 1 --use-imu 0 --use-mvs $usemv --dataset-path ds/$dspath  --dataset-type euroc --cam-calib $calib --config-path $config --save-trajectory euroc 2>&1 | tee output.log; mkdir -p results/$run/$ds/ && mv trajectory.csv results/$run/$ds/tracking.csv && mv output.log *.json results/$run/$ds/
export ds=MOO05    dspath=MOO05_inspect_easy      calib=data/msd/msdmo_calib.json           config=data/msd/msdmo_config_vo$confext.json
echo ">>> [$run - $ds]" && time ./build/basalt_vio --show-gui 0 --deterministic 1 --use-imu 0 --use-mvs $usemv --dataset-path ds/$dspath  --dataset-type euroc --cam-calib $calib --config-path $config --save-trajectory euroc 2>&1 | tee output.log; mkdir -p results/$run/$ds/ && mv trajectory.csv results/$run/$ds/tracking.csv && mv output.log *.json results/$run/$ds/
export ds=MOO07    dspath=MOO07_mapping_easy      calib=data/msd/msdmo_calib.json           config=data/msd/msdmo_config_vo$confext.json
echo ">>> [$run - $ds]" && time ./build/basalt_vio --show-gui 0 --deterministic 1 --use-imu 0 --use-mvs $usemv --dataset-path ds/$dspath  --dataset-type euroc --cam-calib $calib --config-path $config --save-trajectory euroc 2>&1 | tee output.log; mkdir -p results/$run/$ds/ && mv trajectory.csv results/$run/$ds/tracking.csv && mv output.log *.json results/$run/$ds/
export ds=TR1      dspath=dataset-room1_512_16    calib=data/tum/tumvi_512_ds_calib.json    config=data/tum/tumvi_512_config_vo$confext.json
echo ">>> [$run - $ds]" && time ./build/basalt_vio --show-gui 0 --deterministic 1 --use-imu 0 --use-mvs $usemv --dataset-path ds/$dspath  --dataset-type euroc --cam-calib $calib --config-path $config --save-trajectory euroc 2>&1 | tee output.log; mkdir -p results/$run/$ds/ && mv trajectory.csv results/$run/$ds/tracking.csv && mv output.log *.json results/$run/$ds/
export ds=TR2      dspath=dataset-room2_512_16    calib=data/tum/tumvi_512_ds_calib.json    config=data/tum/tumvi_512_config_vo$confext.json
echo ">>> [$run - $ds]" && time ./build/basalt_vio --show-gui 0 --deterministic 1 --use-imu 0 --use-mvs $usemv --dataset-path ds/$dspath  --dataset-type euroc --cam-calib $calib --config-path $config --save-trajectory euroc 2>&1 | tee output.log; mkdir -p results/$run/$ds/ && mv trajectory.csv results/$run/$ds/tracking.csv && mv output.log *.json results/$run/$ds/
export ds=TR3      dspath=dataset-room3_512_16    calib=data/tum/tumvi_512_ds_calib.json    config=data/tum/tumvi_512_config_vo$confext.json
echo ">>> [$run - $ds]" && time ./build/basalt_vio --show-gui 0 --deterministic 1 --use-imu 0 --use-mvs $usemv --dataset-path ds/$dspath  --dataset-type euroc --cam-calib $calib --config-path $config --save-trajectory euroc 2>&1 | tee output.log; mkdir -p results/$run/$ds/ && mv trajectory.csv results/$run/$ds/tracking.csv && mv output.log *.json results/$run/$ds/
export ds=TR4      dspath=dataset-room4_512_16    calib=data/tum/tumvi_512_ds_calib.json    config=data/tum/tumvi_512_config_vo$confext.json
echo ">>> [$run - $ds]" && time ./build/basalt_vio --show-gui 0 --deterministic 1 --use-imu 0 --use-mvs $usemv --dataset-path ds/$dspath  --dataset-type euroc --cam-calib $calib --config-path $config --save-trajectory euroc 2>&1 | tee output.log; mkdir -p results/$run/$ds/ && mv trajectory.csv results/$run/$ds/tracking.csv && mv output.log *.json results/$run/$ds/
export ds=TR5      dspath=dataset-room5_512_16    calib=data/tum/tumvi_512_ds_calib.json    config=data/tum/tumvi_512_config_vo$confext.json
echo ">>> [$run - $ds]" && time ./build/basalt_vio --show-gui 0 --deterministic 1 --use-imu 0 --use-mvs $usemv --dataset-path ds/$dspath  --dataset-type euroc --cam-calib $calib --config-path $config --save-trajectory euroc 2>&1 | tee output.log; mkdir -p results/$run/$ds/ && mv trajectory.csv results/$run/$ds/tracking.csv && mv output.log *.json results/$run/$ds/
export ds=TR6      dspath=dataset-room6_512_16    calib=data/tum/tumvi_512_ds_calib.json    config=data/tum/tumvi_512_config_vo$confext.json
echo ">>> [$run - $ds]" && time ./build/basalt_vio --show-gui 0 --deterministic 1 --use-imu 0 --use-mvs $usemv --dataset-path ds/$dspath  --dataset-type euroc --cam-calib $calib --config-path $config --save-trajectory euroc 2>&1 | tee output.log; mkdir -p results/$run/$ds/ && mv trajectory.csv results/$run/$ds/tracking.csv && mv output.log *.json results/$run/$ds/

export run=of usemv=0 confext=""
export ds=EMH01    dspath=MH_01_easy              calib=data/euroc/euroc_ds_calib.json      config=data/euroc/euroc_config_vo$confext.json
echo ">>> [$run - $ds]" && time ./build/basalt_vio --show-gui 0 --deterministic 1 --use-imu 0 --use-mvs $usemv --dataset-path ds/$dspath  --dataset-type euroc --cam-calib $calib --config-path $config --save-trajectory euroc 2>&1 | tee output.log; mkdir -p results/$run/$ds/ && mv trajectory.csv results/$run/$ds/tracking.csv && mv output.log *.json results/$run/$ds/
export ds=EMH02    dspath=MH_02_easy              calib=data/euroc/euroc_ds_calib.json      config=data/euroc/euroc_config_vo$confext.json
echo ">>> [$run - $ds]" && time ./build/basalt_vio --show-gui 0 --deterministic 1 --use-imu 0 --use-mvs $usemv --dataset-path ds/$dspath  --dataset-type euroc --cam-calib $calib --config-path $config --save-trajectory euroc 2>&1 | tee output.log; mkdir -p results/$run/$ds/ && mv trajectory.csv results/$run/$ds/tracking.csv && mv output.log *.json results/$run/$ds/
export ds=EMH03    dspath=MH_03_medium            calib=data/euroc/euroc_ds_calib.json      config=data/euroc/euroc_config_vo$confext.json
echo ">>> [$run - $ds]" && time ./build/basalt_vio --show-gui 0 --deterministic 1 --use-imu 0 --use-mvs $usemv --dataset-path ds/$dspath  --dataset-type euroc --cam-calib $calib --config-path $config --save-trajectory euroc 2>&1 | tee output.log; mkdir -p results/$run/$ds/ && mv trajectory.csv results/$run/$ds/tracking.csv && mv output.log *.json results/$run/$ds/
export ds=EMH04    dspath=MH_04_difficult         calib=data/euroc/euroc_ds_calib.json      config=data/euroc/euroc_config_vo$confext.json
echo ">>> [$run - $ds]" && time ./build/basalt_vio --show-gui 0 --deterministic 1 --use-imu 0 --use-mvs $usemv --dataset-path ds/$dspath  --dataset-type euroc --cam-calib $calib --config-path $config --save-trajectory euroc 2>&1 | tee output.log; mkdir -p results/$run/$ds/ && mv trajectory.csv results/$run/$ds/tracking.csv && mv output.log *.json results/$run/$ds/
export ds=EMH05    dspath=MH_05_difficult         calib=data/euroc/euroc_ds_calib.json      config=data/euroc/euroc_config_vo$confext.json
echo ">>> [$run - $ds]" && time ./build/basalt_vio --show-gui 0 --deterministic 1 --use-imu 0 --use-mvs $usemv --dataset-path ds/$dspath  --dataset-type euroc --cam-calib $calib --config-path $config --save-trajectory euroc 2>&1 | tee output.log; mkdir -p results/$run/$ds/ && mv trajectory.csv results/$run/$ds/tracking.csv && mv output.log *.json results/$run/$ds/
export ds=EV101    dspath=V1_01_easy              calib=data/euroc/euroc_ds_calib.json      config=data/euroc/euroc_config_vo$confext.json
echo ">>> [$run - $ds]" && time ./build/basalt_vio --show-gui 0 --deterministic 1 --use-imu 0 --use-mvs $usemv --dataset-path ds/$dspath  --dataset-type euroc --cam-calib $calib --config-path $config --save-trajectory euroc 2>&1 | tee output.log; mkdir -p results/$run/$ds/ && mv trajectory.csv results/$run/$ds/tracking.csv && mv output.log *.json results/$run/$ds/
export ds=EV102    dspath=V1_02_medium            calib=data/euroc/euroc_ds_calib.json      config=data/euroc/euroc_config_vo$confext.json
echo ">>> [$run - $ds]" && time ./build/basalt_vio --show-gui 0 --deterministic 1 --use-imu 0 --use-mvs $usemv --dataset-path ds/$dspath  --dataset-type euroc --cam-calib $calib --config-path $config --save-trajectory euroc 2>&1 | tee output.log; mkdir -p results/$run/$ds/ && mv trajectory.csv results/$run/$ds/tracking.csv && mv output.log *.json results/$run/$ds/
export ds=EV201    dspath=V2_01_easy              calib=data/euroc/euroc_ds_calib.json      config=data/euroc/euroc_config_vo$confext.json
echo ">>> [$run - $ds]" && time ./build/basalt_vio --show-gui 0 --deterministic 1 --use-imu 0 --use-mvs $usemv --dataset-path ds/$dspath  --dataset-type euroc --cam-calib $calib --config-path $config --save-trajectory euroc 2>&1 | tee output.log; mkdir -p results/$run/$ds/ && mv trajectory.csv results/$run/$ds/tracking.csv && mv output.log *.json results/$run/$ds/
export ds=MGO05    dspath=MGO05_inspect_easy      calib=data/msd/msdmg_calib.json           config=data/msd/msdmg_config_vo$confext.json
echo ">>> [$run - $ds]" && time ./build/basalt_vio --show-gui 0 --deterministic 1 --use-imu 0 --use-mvs $usemv --dataset-path ds/$dspath  --dataset-type euroc --cam-calib $calib --config-path $config --save-trajectory euroc 2>&1 | tee output.log; mkdir -p results/$run/$ds/ && mv trajectory.csv results/$run/$ds/tracking.csv && mv output.log *.json results/$run/$ds/
export ds=MGO07    dspath=MGO07_mapping_easy      calib=data/msd/msdmg_calib.json           config=data/msd/msdmg_config_vo$confext.json
echo ">>> [$run - $ds]" && time ./build/basalt_vio --show-gui 0 --deterministic 1 --use-imu 0 --use-mvs $usemv --dataset-path ds/$dspath  --dataset-type euroc --cam-calib $calib --config-path $config --save-trajectory euroc 2>&1 | tee output.log; mkdir -p results/$run/$ds/ && mv trajectory.csv results/$run/$ds/tracking.csv && mv output.log *.json results/$run/$ds/
export ds=MIO05    dspath=MIO05_inspect_easy      calib=data/msd/msdmi_calib.json           config=data/msd/msdmi_config_vo$confext.json
echo ">>> [$run - $ds]" && time ./build/basalt_vio --show-gui 0 --deterministic 1 --use-imu 0 --use-mvs $usemv --dataset-path ds/$dspath  --dataset-type euroc --cam-calib $calib --config-path $config --save-trajectory euroc 2>&1 | tee output.log; mkdir -p results/$run/$ds/ && mv trajectory.csv results/$run/$ds/tracking.csv && mv output.log *.json results/$run/$ds/
export ds=MIO07    dspath=MIO07_mapping_easy      calib=data/msd/msdmi_calib.json           config=data/msd/msdmi_config_vo$confext.json
echo ">>> [$run - $ds]" && time ./build/basalt_vio --show-gui 0 --deterministic 1 --use-imu 0 --use-mvs $usemv --dataset-path ds/$dspath  --dataset-type euroc --cam-calib $calib --config-path $config --save-trajectory euroc 2>&1 | tee output.log; mkdir -p results/$run/$ds/ && mv trajectory.csv results/$run/$ds/tracking.csv && mv output.log *.json results/$run/$ds/
export ds=MOO05    dspath=MOO05_inspect_easy      calib=data/msd/msdmo_calib.json           config=data/msd/msdmo_config_vo$confext.json
echo ">>> [$run - $ds]" && time ./build/basalt_vio --show-gui 0 --deterministic 1 --use-imu 0 --use-mvs $usemv --dataset-path ds/$dspath  --dataset-type euroc --cam-calib $calib --config-path $config --save-trajectory euroc 2>&1 | tee output.log; mkdir -p results/$run/$ds/ && mv trajectory.csv results/$run/$ds/tracking.csv && mv output.log *.json results/$run/$ds/
export ds=MOO07    dspath=MOO07_mapping_easy      calib=data/msd/msdmo_calib.json           config=data/msd/msdmo_config_vo$confext.json
echo ">>> [$run - $ds]" && time ./build/basalt_vio --show-gui 0 --deterministic 1 --use-imu 0 --use-mvs $usemv --dataset-path ds/$dspath  --dataset-type euroc --cam-calib $calib --config-path $config --save-trajectory euroc 2>&1 | tee output.log; mkdir -p results/$run/$ds/ && mv trajectory.csv results/$run/$ds/tracking.csv && mv output.log *.json results/$run/$ds/
export ds=TR1      dspath=dataset-room1_512_16    calib=data/tum/tumvi_512_ds_calib.json    config=data/tum/tumvi_512_config_vo$confext.json
echo ">>> [$run - $ds]" && time ./build/basalt_vio --show-gui 0 --deterministic 1 --use-imu 0 --use-mvs $usemv --dataset-path ds/$dspath  --dataset-type euroc --cam-calib $calib --config-path $config --save-trajectory euroc 2>&1 | tee output.log; mkdir -p results/$run/$ds/ && mv trajectory.csv results/$run/$ds/tracking.csv && mv output.log *.json results/$run/$ds/
export ds=TR2      dspath=dataset-room2_512_16    calib=data/tum/tumvi_512_ds_calib.json    config=data/tum/tumvi_512_config_vo$confext.json
echo ">>> [$run - $ds]" && time ./build/basalt_vio --show-gui 0 --deterministic 1 --use-imu 0 --use-mvs $usemv --dataset-path ds/$dspath  --dataset-type euroc --cam-calib $calib --config-path $config --save-trajectory euroc 2>&1 | tee output.log; mkdir -p results/$run/$ds/ && mv trajectory.csv results/$run/$ds/tracking.csv && mv output.log *.json results/$run/$ds/
export ds=TR3      dspath=dataset-room3_512_16    calib=data/tum/tumvi_512_ds_calib.json    config=data/tum/tumvi_512_config_vo$confext.json
echo ">>> [$run - $ds]" && time ./build/basalt_vio --show-gui 0 --deterministic 1 --use-imu 0 --use-mvs $usemv --dataset-path ds/$dspath  --dataset-type euroc --cam-calib $calib --config-path $config --save-trajectory euroc 2>&1 | tee output.log; mkdir -p results/$run/$ds/ && mv trajectory.csv results/$run/$ds/tracking.csv && mv output.log *.json results/$run/$ds/
export ds=TR4      dspath=dataset-room4_512_16    calib=data/tum/tumvi_512_ds_calib.json    config=data/tum/tumvi_512_config_vo$confext.json
echo ">>> [$run - $ds]" && time ./build/basalt_vio --show-gui 0 --deterministic 1 --use-imu 0 --use-mvs $usemv --dataset-path ds/$dspath  --dataset-type euroc --cam-calib $calib --config-path $config --save-trajectory euroc 2>&1 | tee output.log; mkdir -p results/$run/$ds/ && mv trajectory.csv results/$run/$ds/tracking.csv && mv output.log *.json results/$run/$ds/
export ds=TR5      dspath=dataset-room5_512_16    calib=data/tum/tumvi_512_ds_calib.json    config=data/tum/tumvi_512_config_vo$confext.json
echo ">>> [$run - $ds]" && time ./build/basalt_vio --show-gui 0 --deterministic 1 --use-imu 0 --use-mvs $usemv --dataset-path ds/$dspath  --dataset-type euroc --cam-calib $calib --config-path $config --save-trajectory euroc 2>&1 | tee output.log; mkdir -p results/$run/$ds/ && mv trajectory.csv results/$run/$ds/tracking.csv && mv output.log *.json results/$run/$ds/
export ds=TR6      dspath=dataset-room6_512_16    calib=data/tum/tumvi_512_ds_calib.json    config=data/tum/tumvi_512_config_vo$confext.json
echo ">>> [$run - $ds]" && time ./build/basalt_vio --show-gui 0 --deterministic 1 --use-imu 0 --use-mvs $usemv --dataset-path ds/$dspath  --dataset-type euroc --cam-calib $calib --config-path $config --save-trajectory euroc 2>&1 | tee output.log; mkdir -p results/$run/$ds/ && mv trajectory.csv results/$run/$ds/tracking.csv && mv output.log *.json results/$run/$ds/

source $xrtmet/.venv/bin/activate.fish
$xrtmet/batch.py results/ $xrtmet/test/data/targets --metrics success ate rte --verbose --save_file batch.json
